###################################################################################################
# DOCKER COMPOSE FILE FOR WHISPR MESSENGER DEVELOPMENT ENVIRONMENT                                #
###################################################################################################
# - This file sets up the development environment with PostgreSQL, Redis, and the Backend         #
# - This configuration depends on a .env file in the same directory for environment variables     #
#   Ensure to create a .env file with the necessary variables before running this setup.          #
###################################################################################################

name: whispr-messenger

services:
  postgres:
    image: postgres:15-alpine
    container_name: whispr-dev-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - whispr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: whispr-dev-redis
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - whispr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  nestjs:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: whispr-dev-api
    env_file: .env
    volumes:
      - ../..:/workspace:cached
      - node_modules_volume:/workspace/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    # command: sleep infinity  # Keep container running for dev
    ports:
      - "3001:${HTTP_PORT}"   # NestJS
      - "9229:9229"   # Debugger
    networks:
      - whispr-network
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${HTTP_PORT}/api/v1/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  node_modules_volume:
  postgres_data:
  redis_data:

networks:
  whispr-network:
    driver: bridge
